name: Build and Deploy quarto-getstartedgithub

on:
  push:
    branches: [main]
    paths:
      - 'books/github/**'
      - '.github/workflows/quarto-getstartedgithub.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Book
        run: |
          cd books/github
          quarto render

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: books/github/_book
